services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=host=db port=5432 dbname=app user=user password=password
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    command: ["postgres", "-c", "log_statement=all"]
